In [2]:
import numpy as np

In [4]:
arr1 = np.array([1, 2, 3, 4, 5])
print(arr1)

[1 2 3 4 5]


In [7]:
print(type(arr1))
arr1.shape

<class 'numpy.ndarray'>


(5,)

In [9]:
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
arr2.reshape(6,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [11]:
np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [13]:
identity_martix = np.eye(3)

In [14]:
identity_martix.ndim

2